package it.gabriele.truckflow.deadlineservice.domain;

/** Codice stabile e indipendente dal dominio principale per ogni elemento gestito. */
public enum ManagedElementCode {
  VEHICLE_REGISTRATION_DOCUMENT,
  VEHICLE_INSURANCE,
  VEHICLE_ROADWORTHINESS_TEST,
  VEHICLE_TACHOGRAPH_DEVICE_DEADLINE,
  VEHICLE_ATP_CERTIFICATION,
  VEHICLE_ADR_CERTIFICATION,

  DRIVER_LICENSE,
  DRIVER_CQC,
  DRIVER_TACHOGRAPH_CARD,
  DRIVER_MEDICAL_CHECK,
  DRIVER_MANDATORY_TRAINING,

  VEHICLE_ENGINE_OIL,
  VEHICLE_FILTERS,
  VEHICLE_AIR_FILTER,
  VEHICLE_OIL_FILTER,
  VEHICLE_FUEL_FILTER,
  VEHICLE_BRAKES,
  VEHICLE_BRAKE_PADS,
  VEHICLE_BRAKE_DISCS,
  VEHICLE_COOLANT,
  VEHICLE_ADBLUE_SYSTEM,
  VEHICLE_BELTS,
  VEHICLE_BATTERY,
  VEHICLE_SUSPENSION,
  VEHICLE_LIGHTS,
  VEHICLE_ENGINE_DIAGNOSTIC,

  TRAILER_BRAKING_SYSTEM,
  TRAILER_ELECTRICAL_SYSTEM,
  TRAILER_REFRIGERATION_UNIT,
  TRAILER_BODY_FLOOR,
  TRAILER_DOORS_LOCKS,
  TRAILER_FIFTH_WHEEL_COUPLING,
  TRAILER_TAIL_LIFT,
  TRAILER_LANDING_GEAR,

  CARGO_PALLET,
  CARGO_CONTAINER,
  CARGO_PACKAGING,
  CARGO_SEAL,
  CARGO_LABEL,
  CARGO_DECLARED_VS_ACTUAL_WEIGHT,

  WAREHOUSE_LOCATION,
  WAREHOUSE_AISLES_RACKS,
  WAREHOUSE_COLD_CELL,
  WAREHOUSE_EQUIPMENT,
  WAREHOUSE_SAFETY_SYSTEM,

  TRIP_POINTS_OF_INTEREST,
  TRIP_ROAD_RESTRICTION,
  TRIP_WEATHER_CONDITION,
  TRIP_TOLL,
  TRIP_ESTIMATED_VS_ACTUAL_TIME,

  SECURITY_LOCK,
  SECURITY_ALARM,
  SECURITY_INTRUSION_SENSOR,
  SECURITY_ONBOARD_CAMERA,

  TELEMATICS_CANBUS_SENSOR,
  TELEMATICS_DTC_ENGINE_ERROR,
  TELEMATICS_TEMPERATURE,
  TELEMATICS_TPMS_PRESSURE,
  TELEMATICS_REAL_FUEL_CONSUMPTION,
  TELEMATICS_DOOR_STATUS,
  TELEMATICS_UNAUTHORIZED_OPENING
}
