package it.gabriele.truckflow.domain.fleet;

/** Caratteristiche tecniche speciali del mezzo/allestimento. */
public enum VehicleTechnicalFeature {
  SELF_STEERING_AXLE,
  STEERING_AXLE,
  LIFTABLE_AXLE,
  DOUBLE_DECK,
  MEGA_VOLUME,
  LOW_DECK,
  AIR_SUSPENSION,
  EXTENDABLE_CHASSIS,
  GOOSENECK,
  LOW_BED_CRADLE,
  TWIST_LOCKS,
  ATP_CERTIFIED,
  XL_CERTIFIED,
  ADR_APPROVED,
  ACTIVE_REFRIGERATION,
  TEMPERATURE_RECORDER,
  HAY_RACKS,
  AGRICULTURAL_APPROVAL,
  STAINLESS_STEEL_TANK,
  FOOD_GRADE_TANK;
}
