package it.gabriele.truckflow.domain.cargo;

public enum CargoTransportRequirement {
  REFRIGERATED_VEHICLE_REQUIRED,
  FROZEN_TRANSPORT_REQUIRED,
  TEMPERATURE_CONTROL_REQUIRED,
  ADR_VEHICLE_REQUIRED,
  ATP_CERTIFICATION_REQUIRED,
  FOOD_GRADE_BODY_REQUIRED,
  PHARMA_GRADE_REQUIRED,
  WASTE_AUTHORIZATION_REQUIRED,
  LIVESTOCK_BODY_REQUIRED,
  BULK_BODY_REQUIRED,
  TANK_BODY_REQUIRED,
  CONTAINER_CHASSIS_REQUIRED,
  CAR_CARRIER_REQUIRED,
  LOW_LOADER_REQUIRED,
  SIDE_LOADING_REQUIRED,
  REAR_LOADING_REQUIRED,
  SEPARATION_REQUIRED
}
