package it.gabriele.truckflow.domain.vehicles.operation;

public enum VehicleCapability {
  ADR,
  ATP,
  REEFER_UNIT,
  TEMPERATURE_CONTROLLED,
  DUAL_TEMPERATURE,
  HYDRAULIC_TAIL_LIFT,
  HYDRAULIC_RAMP,
  SLIDING_ROOF,
  SLIDING_CURTAINS,
  DOUBLE_DECK,
  COIL_WELL,
  BULK_TRANSPORT,
  SIDE_LOADER,
  REAR_LOADER,
  CONTAINER_LOCKS,
  FOODGRADE_TANK,
  CHEMICAL_TANK,
  FUEL_TANK,
  LOW_LOADER,
  HEAVY_DUTY,
  EXCEPTIONAL_TRANSPORT,
  CAR_TRANSPORT,
  LIVESTOCK_TRANSPORT
}
