package it.gabriele.truckflow.domain.shipments;

public enum ShipmentTransportRequirement {
  ADR_REQUIRED,
  ATP_REQUIRED,
  FOOD_GRADE_REQUIRED,
  PHARMA_GRADE_REQUIRED,
  WASTE_AUTHORIZATION_REQUIRED,
  LIVESTOCK_AUTHORIZATION_REQUIRED,
  TEMPERATURE_CONTROL_REQUIRED,
  REFRIGERATED_TRANSPORT_REQUIRED,
  FROZEN_TRANSPORT_REQUIRED,
  SEPARATION_REQUIRED,
  HIGH_VALUE_HANDLING_REQUIRED,
  FRAGILE_HANDLING_REQUIRED,
  DEDICATED_VEHICLE_REQUIRED,
  EXPRESS_HANDLING_REQUIRED,
  SPECIAL_HANDLING_REQUIRED
}
