package it.gabriele.truckflow.domain.vehicles;

public enum VehicleOperationalRole {
  LINE_HAUL,
  DISTRIBUTION,
  LAST_MILE,
  GROUPAGE,
  FULL_LOAD,
  ADR_TRANSPORT,
  REFRIGERATED_TRANSPORT,
  BULK_TRANSPORT,
  CONTAINER_TRANSPORT,
  COIL_TRANSPORT,
  HEAVY_DUTY,
  SPECIAL_TRANSPORT,
  CAR_TRANSPORT,
  WAREHOUSE_SUPPORT,
  FLEET_SUPPORT,
  MAINTENANCE_SUPPORT
}
