package it.gabriele.truckflow.domain.company;

public enum CompanyLicenseType {
  ROAD_HAULAGE_REGISTER,
  REN,
  COMMUNITY_LICENSE,
  OWN_ACCOUNT_LICENSE,
  ENVIRONMENTAL_MANAGERS_REGISTER_CATEGORY_2_BIS,
  ENVIRONMENTAL_MANAGERS_REGISTER_CATEGORY_4,
  ENVIRONMENTAL_MANAGERS_REGISTER_CATEGORY_5
}
