package it.gabriele.truckflow.domain.compliance;

public enum ComplianceRequirementType {
  DOCUMENT_REQUIRED,
  QUALIFICATION_REQUIRED,
  VEHICLE_CAPABILITY_REQUIRED,
  VEHICLE_CERTIFICATION_REQUIRED,
  CARGO_REGULATORY_REQUIRED,
  TEMPERATURE_CONTROL_REQUIRED,
  SAFETY_REQUIREMENT,
  LEGAL_REQUIREMENT,
  INTERNAL_POLICY,
  CUSTOMER_REQUIREMENT
}
